(()=>{
'use strict';
if(window.__civicoAdminAI)return;window.__civicoAdminAI=true;
const q=s=>document.querySelector(s),qa=s=>[...document.querySelectorAll(s)];
let aiHistory=[];

function styles(){if(q('#adminAIStyles'))return;document.head.insertAdjacentHTML('beforeend',`<style id="adminAIStyles">
#aiSec{--ai-ink:#16302b;--ai-green:#2f6f62;--ai-soft:#edf5f2}.ai-shell{display:grid;grid-template-columns:minmax(0,1fr) 290px;gap:16px;align-items:start}.ai-main,.ai-side{background:#fff;border:1px solid var(--line);border-radius:18px;box-shadow:0 7px 22px rgba(23,55,48,.045)}.ai-main{overflow:hidden}.ai-head{padding:18px 18px 14px;border-bottom:1px solid var(--line);display:flex;align-items:flex-start;justify-content:space-between;gap:12px}.ai-head h1{font-size:30px;margin:0}.ai-pill{display:inline-flex;align-items:center;gap:6px;padding:6px 9px;border-radius:999px;background:#edf8f3;color:#266548;font-size:10px;font-weight:900;white-space:nowrap}.ai-chat{min-height:380px;max-height:58vh;overflow:auto;padding:18px;display:flex;flex-direction:column;gap:12px;background:linear-gradient(180deg,#fbfdfc,#f7faf8)}.ai-msg{max-width:min(760px,88%);padding:12px 14px;border-radius:16px;line-height:1.5;font-size:13px;white-space:pre-wrap;word-break:break-word}.ai-msg.assistant{align-self:flex-start;background:#fff;border:1px solid var(--line);border-bottom-left-radius:5px}.ai-msg.user{align-self:flex-end;background:var(--green);color:#fff;border-bottom-right-radius:5px}.ai-msg.loading{color:var(--muted);font-style:italic}.ai-compose{padding:14px;border-top:1px solid var(--line);background:#fff}.ai-form{display:grid;grid-template-columns:1fr auto;gap:9px;align-items:end}.ai-form textarea{min-height:52px;max-height:150px;resize:vertical}.ai-send{min-width:104px;height:52px}.ai-hint{margin:7px 2px 0;color:var(--muted);font-size:10.5px}.ai-side{padding:16px}.ai-side h2{font-size:22px;margin:0 0 4px}.ai-side p{font-size:11px;color:var(--muted);line-height:1.5;margin:0 0 12px}.ai-prompts{display:grid;gap:8px}.ai-prompt{border:1px solid var(--line);background:#fff;color:var(--ink);border-radius:12px;padding:10px 11px;text-align:left;font-size:11px;font-weight:800}.ai-prompt:hover{background:var(--ai-soft);border-color:#cfe2db}.ai-scope{margin-top:14px;padding:11px;border-radius:12px;background:#f7faf8;border:1px solid var(--line);font-size:10.5px;color:var(--muted);line-height:1.5}.ai-scope b{color:var(--ink)}.ai-reset{margin-top:10px;width:100%}.ai-error-card{background:#fff5e9!important;border-color:#e4b881!important;color:#80552d!important}.ai-error-card b{display:block;margin-bottom:4px;color:#684223}@media(max-width:850px){.ai-shell{grid-template-columns:1fr}.ai-side{order:-1}.ai-prompts{grid-template-columns:1fr 1fr}.ai-chat{max-height:none;min-height:330px}}@media(max-width:560px){.ai-head{padding:15px;flex-direction:column}.ai-head h1{font-size:27px}.ai-chat{padding:12px;min-height:320px}.ai-msg{max-width:94%;font-size:12.5px}.ai-form{grid-template-columns:1fr}.ai-send{width:100%;height:44px}.ai-prompts{grid-template-columns:1fr}.ai-side{padding:13px}}
</style>`)}

function activate(){qa('.navtab').forEach(x=>x.classList.toggle('active',x.dataset.section==='aiSec'));qa('.section').forEach(s=>s.classList.toggle('active',s.id==='aiSec'));setTimeout(()=>q('#aiInput')?.focus(),50)}
function ensureUI(){if(q('#aiSec'))return;styles();const tabs=q('.navtabs');if(!tabs)return;const statsTab=q('.navtab[data-section="statsSec"]'),syncTab=q('.navtab[data-section="syncSec"]');const tab=document.createElement('button');tab.className='navtab';tab.dataset.section='aiSec';tab.textContent='Assistente AI';tab.onclick=activate;if(statsTab)statsTab.insertAdjacentElement('afterend',tab);else if(syncTab)tabs.insertBefore(tab,syncTab);else tabs.appendChild(tab);
 const anchor=q('#syncSec')||q('#requestsSec');if(!anchor)return;anchor.insertAdjacentHTML('beforebegin',`<section id="aiSec" class="section"><div class="ai-shell"><div class="ai-main"><div class="ai-head"><div><div class="muted">Analisi gestionale in sola lettura</div><h1>Assistente AI</h1></div><span class="ai-pill">● Solo dati aggregati</span></div><div id="aiChat" class="ai-chat" aria-live="polite"></div><div class="ai-compose"><form id="aiForm" class="ai-form"><textarea id="aiInput" maxlength="4000" placeholder="Chiedi qualcosa sui dati di Civico 26…" required></textarea><button id="aiSend" class="btn primary ai-send" type="submit">Invia</button></form><div class="ai-hint">L’assistente può analizzare i dati, ma non può modificare prenotazioni o tariffe.</div></div></div><aside class="ai-side"><h2>Domande rapide</h2><p>Prova una di queste analisi. Puoi poi continuare la conversazione liberamente.</p><div class="ai-prompts"><button class="ai-prompt" type="button">Come sta andando questo mese?</button><button class="ai-prompt" type="button">Confronta questo mese con il precedente.</button><button class="ai-prompt" type="button">Quale canale sta rendendo di più?</button><button class="ai-prompt" type="button">Dove sto perdendo più margine?</button><button class="ai-prompt" type="button">Fammi un riepilogo dell’anno.</button><button class="ai-prompt" type="button">Ci sono periodi futuri che sembrano sottoprezzati?</button></div><div class="ai-scope"><b>Cosa legge</b><br>Occupazione, soggiorni, canali, tariffe, ricavi e costi aggregati. Nomi, email, telefoni e note degli ospiti non vengono inviati al modello.</div><button id="aiReset" class="btn light ai-reset" type="button">Nuova conversazione</button></aside></div></section>`);
 q('#aiForm').addEventListener('submit',e=>{e.preventDefault();send(q('#aiInput').value)});qa('.ai-prompt').forEach(b=>b.onclick=()=>send(b.textContent.trim()));q('#aiReset').onclick=reset;reset();}

function bubble(role,text,extra=''){const chat=q('#aiChat');if(!chat)return null;const el=document.createElement('div');el.className=`ai-msg ${role}${extra?' '+extra:''}`;el.textContent=text;chat.appendChild(el);chat.scrollTop=chat.scrollHeight;return el}
function reset(){aiHistory=[];const chat=q('#aiChat');if(chat)chat.innerHTML='';bubble('assistant','Ciao. Posso leggere le statistiche aggregate di Civico 26 e aiutarti a interpretare occupazione, ricavi, costi, ADR, canali e tariffe. Da cosa vuoi partire?');const input=q('#aiInput');if(input)input.value=''}
function setBusy(on){const btn=q('#aiSend'),input=q('#aiInput');if(btn){btn.disabled=on;btn.textContent=on?'Analizzo…':'Invia'}if(input)input.disabled=on}
function setupError(text){const el=bubble('assistant','', 'ai-error-card');if(!el)return;const b=document.createElement('b');b.textContent='Assistente pronto, manca solo l’attivazione API.';const span=document.createElement('span');span.textContent=' '+text;el.append(b,span)}
function errorText(data,status){const main=typeof data?.error==='string'?data.error:(typeof data?.error?.message==='string'?data.error.message:(typeof data?.message==='string'?data.message:'HTTP '+status));const detail=typeof data?.detail==='string'?data.detail.trim():'';return detail&&detail!==main?main+': '+detail:main}

async function send(raw){const message=String(raw||'').trim();if(!message||q('#aiSend')?.disabled)return;const input=q('#aiInput');if(input)input.value='';bubble('user',message);const loading=bubble('assistant','Sto analizzando i dati…','loading');setBusy(true);try{const {data:{session}}=await sb.auth.getSession();if(!session?.access_token)throw new Error('Sessione non valida. Esci e accedi di nuovo.');const resp=await fetch(SUPABASE_URL+'/functions/v1/admin-ai',{method:'POST',headers:{'Content-Type':'application/json','apikey':SUPABASE_KEY,'Authorization':'Bearer '+session.access_token},body:JSON.stringify({message,history:aiHistory.slice(-8)})});const data=await resp.json().catch(()=>({}));loading?.remove();if(!resp.ok){if(data?.code==='AI_NOT_CONFIGURED'){setupError(errorText(data,resp.status));return}throw new Error(errorText(data,resp.status))}const reply=String(data?.reply||'Non ho ricevuto una risposta valida.');bubble('assistant',reply);aiHistory.push({role:'user',content:message},{role:'assistant',content:reply});if(aiHistory.length>10)aiHistory=aiHistory.slice(-10)}catch(err){loading?.remove();bubble('assistant','Non riesco a completare l’analisi: '+(err?.message||String(err)),'ai-error-card')}finally{setBusy(false);input?.focus()}}

function boot(){ensureUI();if(!q('#aiSec'))setTimeout(boot,250)}
boot();
})();
