(()=>{
'use strict';
const q=s=>document.querySelector(s),qa=s=>[...document.querySelectorAll(s)];
const safe=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const phoneHref=p=>p?`https://wa.me/${String(p).replace(/\D/g,'')}`:null;
function goSection(id){const tab=q(`.navtab[data-section="${id}"]`);if(tab){tab.click();setTimeout(()=>q(`#${id}`)?.scrollIntoView({behavior:'smooth',block:'start'}),50)}}
function goForm(form){goSection('calendarSec');setTimeout(()=>{q(`[data-form="${form}"]`)?.click();q(`#${form}`)?.scrollIntoView({behavior:'smooth',block:'start'})},100)}
function ensureDashboard(){if(q('#adminDashboard'))return;const head=q('.admin-head');if(!head)return;head.insertAdjacentHTML('afterend',`<section id="adminDashboard" class="admin-dashboard"><div class="dash-grid"><div class="dash-card"><span class="dash-label">Prossimo check-in</span><strong class="dash-value" id="dashCheckin">—</strong><span class="dash-sub" id="dashCheckinSub">Nessuno</span></div><div class="dash-card"><span class="dash-label">Prossimo check-out</span><strong class="dash-value" id="dashCheckout">—</strong><span class="dash-sub" id="dashCheckoutSub">Nessuno</span></div><div class="dash-card"><span class="dash-label">Richieste nuove</span><strong class="dash-value" id="dashRequests">0</strong><span class="dash-sub">Da gestire</span></div><div class="dash-card"><span class="dash-label">Prenotazioni future</span><strong class="dash-value" id="dashFuture">0</strong><span class="dash-sub">Ancora da concludere</span></div><div class="dash-card"><span class="dash-label">Sincronizzazione</span><strong class="dash-value" id="dashSync">—</strong><span class="dash-sub" id="dashSyncSub">Calendari OTA</span></div></div><div class="quick-actions"><button class="btn" data-quick="booking">＋ Prenotazione</button><button class="btn" data-quick="block">⛔ Blocca date</button><button class="btn" data-quick="requests">✉ Richieste</button><button class="btn" data-quick="price">€ Tariffa</button></div></section>`);q('[data-quick="booking"]').onclick=()=>goForm('bookingPanel');q('[data-quick="block"]').onclick=()=>goForm('blockPanel');q('[data-quick="requests"]').onclick=()=>goSection('requestsSec');q('[data-quick="price"]').onclick=()=>goSection('pricesSec')}
function renderDashboard(){ensureDashboard();if(typeof entries==='undefined')return;const today=dateKey(new Date());const future=entries.filter(e=>e.status==='booked'&&e.end_date>today).sort((a,b)=>a.start_date.localeCompare(b.start_date));const nextIn=future.find(e=>e.start_date>=today)||future[0];const nextOut=future.find(e=>e.end_date>=today)||future[0];q('#dashFuture').textContent=future.length;q('#dashRequests').textContent=(requests||[]).filter(r=>r.status==='new').length;if(nextIn){q('#dashCheckin').textContent=fmt(nextIn.start_date);q('#dashCheckinSub').textContent=nextIn.guest_name||'Ospite'}else{q('#dashCheckin').textContent='—';q('#dashCheckinSub').textContent='Nessuno'}if(nextOut){q('#dashCheckout').textContent=fmt(nextOut.end_date);q('#dashCheckoutSub').textContent=nextOut.guest_name||'Ospite'}else{q('#dashCheckout').textContent='—';q('#dashCheckoutSub').textContent='Nessuno'}const active=(feeds||[]).filter(f=>f.is_active!==false),errors=active.filter(f=>f.last_error);q('#dashSync').textContent=!active.length?'Nessuno':errors.length?`${errors.length} errore${errors.length===1?'':'i'}`:'OK';q('#dashSyncSub').textContent=active.length?`${active.length} calendario${active.length===1?'':'i'} collegato${active.length===1?'':'i'}`:'Nessun feed OTA'}
function markRichItems(){qa('.item').forEach(i=>i.classList.add('admin-rich'))}
function highlightRange(){const start=$('blockStart')?.value,end=$('blockEnd')?.value;const buttons=qa('#adminCalendar .day');buttons.forEach(b=>b.classList.remove('sel-range'));if(!start||!end||!buttons.length)return;const first=new Date(view.getFullYear(),view.getMonth(),1),offset=(first.getDay()+6)%7,gridStart=new Date(first.getTime()-offset*DAY);buttons.forEach((b,i)=>{const k=dateKey(new Date(gridStart.getTime()+i*DAY));if(k>=start&&k<=end)b.classList.add('sel-range')})}
function contactLinks(r){const parts=[];if(r?.guest_phone){const wa=phoneHref(r.guest_phone);if(wa)parts.push(`<a class="contact-link wa" target="_blank" rel="noopener" href="${wa}">WhatsApp</a>`)}if(r?.guest_email)parts.push(`<a class="contact-link mail" href="mailto:${encodeURIComponent(r.guest_email)}">Email</a>`);return parts.length?`<div class="contact-actions">${parts.join('')}</div>`:''}
function enhancedFuture(){const list=$('futureBookingsList');if(!list)return;const today=dateKey(new Date());const future=entries.filter(e=>e.status==='booked'&&e.end_date>today).sort((a,b)=>a.start_date.localeCompare(b.start_date)||a.end_date.localeCompare(b.end_date));const direct=future.filter(e=>e.source==='direct'&&!e.external_feed_id),ota=future.filter(e=>e.source==='booking'||e.source==='airbnb'||!!e.external_feed_id);$('futureCount').textContent=future.length;$('futureDirectCount').textContent=direct.length;$('futureOtaCount').textContent=ota.length;list.innerHTML='';if(!future.length){list.innerHTML='<div class="empty">Nessuna prenotazione futura.</div>';return}const sm={direct:'Diretta',booking:'Booking.com',airbnb:'Airbnb',manual:'Manuale',other:'Altro'};future.forEach(e=>{const r=requests.find(x=>Number(x.confirmed_entry_id)===Number(e.id)),d=document.createElement('div'),source=sm[e.source]||e.source||'Altro',nights=Math.max(1,Math.round((parseDate(e.end_date)-parseDate(e.start_date))/DAY)),title=e.guest_name||r?.guest_name||'Ospite';d.className=`item admin-rich ${e.source==='booking'?'source-booking':e.source==='airbnb'?'source-airbnb':'source-direct'}`;let meta=`${fmt(e.start_date)} → ${fmt(e.end_date)} · ${nights} ${nights===1?'notte':'notti'} · ${safe(source)}`;if(r){meta+=`<br>Codice: ${safe(r.request_code)} · ${r.guests} ospiti · € ${Number(r.estimated_total).toFixed(0)} indicativi`;meta+=`<br>Email: ${safe(r.guest_email||'—')}${r.guest_phone?` · Tel/WhatsApp: ${safe(r.guest_phone)}`:''}`}else if(e.note)meta+=`<br>${safe(e.note)}`;else if(e.external_feed_id)meta+='<br>Dettagli ospite non disponibili nel feed iCal.';d.innerHTML=`<div><span class="badge ${e.source==='direct'&&!e.external_feed_id?'booked':'sync'}">${safe(source)}</span><strong>${safe(title)}</strong><div class="meta">${meta}</div>${contactLinks(r)}</div><div class="row-actions"></div>`;const a=d.querySelector('.row-actions');if(e.source==='direct'&&!e.external_feed_id){const edit=document.createElement('button');edit.className='btn light small';edit.textContent='Modifica';edit.onclick=()=>editEntry(e);const cancel=document.createElement('button');cancel.className='btn danger small';cancel.textContent='Annulla';cancel.onclick=()=>cancelDirectBooking(e,r);a.append(edit,cancel)}else{const note=document.createElement('span');note.className='muted';note.textContent='Gestita dalla piattaforma';a.appendChild(note)}list.appendChild(d)})}
function enhancedRequests(){const list=$('requestsList');if(!list)return;const active=requests.filter(r=>r.status==='new'||r.status==='waiting').length;$('requestCountBadge').textContent=active?`(${active})`:'';$('reqNewCount').textContent=requests.filter(r=>r.status==='new').length;$('reqWaitingCount').textContent=requests.filter(r=>r.status==='waiting').length;$('reqConfirmedCount').textContent=requests.filter(r=>r.status==='confirmed').length;list.innerHTML='';if(!requests.length){list.innerHTML='<div class="empty">Nessuna richiesta dal sito.</div>';renderDashboard();return}requests.forEach(r=>{const d=document.createElement('div'),when=new Intl.DateTimeFormat('it-IT',{dateStyle:'short',timeStyle:'short'}).format(new Date(r.created_at)),total=Number(r.estimated_total).toFixed(0);d.className=`item admin-rich request-${r.status}`;d.innerHTML=`<div><span class="badge ${r.status==='confirmed'?'booked':(r.status==='rejected'||r.status==='cancelled')?'blocked':'sync'}">${safe(requestStatusLabel(r.status))}</span><strong>Richiesta ${safe(r.request_code)} · ${safe(r.guest_name||'Ospite')}</strong><div class="meta">${fmt(r.check_in)} → ${fmt(r.check_out)} · ${r.guests} ospiti · € ${total} indicativi · ricevuta ${safe(when)}<br>Email: ${safe(r.guest_email||'—')}${r.guest_phone?` · Tel/WhatsApp: ${safe(r.guest_phone)}`:''}</div>${contactLinks(r)}</div><div class="row-actions"></div>`;const actions=d.querySelector('.row-actions');if(r.status!=='confirmed'&&r.status!=='cancelled'){if(r.status==='new'){const b=document.createElement('button');b.className='btn light small';b.textContent='In attesa';b.onclick=()=>setRequestStatus(r.id,'waiting');actions.appendChild(b)}if(r.status!=='rejected'){const rej=document.createElement('button');rej.className='btn danger small';rej.textContent='Rifiuta';rej.onclick=()=>rejectRequest(r);const conf=document.createElement('button');conf.className='btn primary small';conf.textContent='Conferma';conf.onclick=()=>confirmRequest(r);actions.append(rej,conf)}}else{const done=document.createElement('span');done.className='muted';done.textContent=r.status==='confirmed'?'Calendario bloccato':'Richiesta chiusa';actions.appendChild(done)}list.appendChild(d)});renderDashboard()}
function enhanceFeeds(){qa('#feedsList .item').forEach((d,i)=>{d.classList.add('admin-rich');const f=feeds[i];if(!f)return;const line=d.querySelector('.statusline');if(line&&!d.querySelector('.sync-health')){line.insertAdjacentHTML('afterend',`<span class="sync-health ${f.last_error?'error':'ok'}">${f.last_error?'⚠ Errore':'✓ Sincronizzato'}</span>`)}})}
function bindRange(){['blockStart','blockEnd'].forEach(id=>$(id)?.addEventListener('change',highlightRange))}
function afterRender(){renderDashboard();markRichItems();highlightRange();enhanceFeeds()}
const oldRenderAll=renderAll;renderAll=function(){oldRenderAll();enhancedFuture();enhancedRequests();afterRender()};
const oldRenderCalendar=renderCalendar;renderCalendar=function(){oldRenderCalendar();highlightRange()};
const oldSelectBlockDate=selectBlockDate;selectBlockDate=function(k){oldSelectBlockDate(k);highlightRange()};
renderFutureBookings=enhancedFuture;renderRequests=enhancedRequests;
const oldRenderFeeds=renderFeeds;renderFeeds=function(){oldRenderFeeds();enhanceFeeds();renderDashboard()};
ensureDashboard();bindRange();setTimeout(()=>{if($('adminView')?.style.display!=='none'){enhancedFuture();enhancedRequests();afterRender()}},300);
})();