(()=>{
'use strict';
const q=s=>document.querySelector(s),qa=s=>[...document.querySelectorAll(s)];
const safe=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const phoneHref=p=>p?`https://wa.me/${String(p).replace(/\D/g,'')}`:null;
let futureFilter='all',rangeStart=null,rangeEnd=null,nextCheckinEntry=null,nextCheckoutEntry=null,statsYear=new Date().getFullYear();

function goSection(id){const tab=q(`.navtab[data-section="${id}"]`);if(!tab)return;tab.click();setTimeout(()=>q(`#${id}`)?.scrollIntoView({behavior:'smooth',block:'start'}),50)}
function goForm(form){goSection('calendarSec');setTimeout(()=>{q(`[data-form="${form}"]`)?.click();q(`#${form}`)?.scrollIntoView({behavior:'smooth',block:'start'})},100)}
function platformFor(e){if(['booking','airbnb','direct'].includes(e.source))return e.source;const f=(feeds||[]).find(x=>Number(x.id)===Number(e.external_feed_id));return f?.provider||e.source||'other'}
function sourceLabel(e){return ({direct:'Diretta',booking:'Booking.com',airbnb:'Airbnb',manual:'Manuale',other:'Altro'})[platformFor(e)]||platformFor(e)}
function requestForEntry(e){return (requests||[]).find(x=>Number(x.confirmed_entry_id)===Number(e.id))}
function contactLinks(r){const parts=[];if(r?.guest_phone){const wa=phoneHref(r.guest_phone);if(wa)parts.push(`<a class="contact-link wa" target="_blank" rel="noopener" href="${wa}">WhatsApp</a>`)}if(r?.guest_email)parts.push(`<a class="contact-link mail" href="mailto:${encodeURIComponent(r.guest_email)}">Email</a>`);return parts.length?`<div class="contact-actions">${parts.join('')}</div>`:''}

function injectExtraStyles(){if(q('#adminEnhanceExtraStyles'))return;document.head.insertAdjacentHTML('beforeend',`<style id="adminEnhanceExtraStyles">
.stats-toolbar{display:flex;align-items:end;justify-content:space-between;gap:12px;margin-bottom:14px}.stats-toolbar label{margin:0 0 5px}.stats-year{width:150px}.stats-kpis{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px;margin-bottom:16px}.stats-kpi{background:#fff;border:1px solid var(--line);border-radius:16px;padding:14px;box-shadow:0 7px 20px rgba(23,55,48,.045)}.stats-kpi span{display:block;color:var(--muted);font-size:10px;font-weight:900;text-transform:uppercase;letter-spacing:.05em}.stats-kpi strong{display:block;font-size:25px;line-height:1.15;margin-top:4px}.stats-kpi small{display:block;color:var(--muted);font-size:11px;margin-top:4px}.stats-grid{display:grid;grid-template-columns:1.25fr .75fr;gap:16px}.stats-card{background:#fff;border:1px solid var(--line);border-radius:18px;padding:17px;box-shadow:0 7px 22px rgba(23,55,48,.045)}.stats-card h2{font-size:23px;margin-bottom:4px}.stats-card-sub{color:var(--muted);font-size:11px;margin-bottom:16px}.monthly-chart{height:245px;display:grid;grid-template-columns:repeat(12,minmax(0,1fr));gap:7px;align-items:end;padding-top:12px}.month-col{height:100%;display:flex;flex-direction:column;justify-content:flex-end;align-items:center;gap:5px;min-width:0}.month-value{font-size:9px;font-weight:800;color:var(--muted);height:14px}.month-track{height:185px;width:100%;max-width:34px;background:#eef4f2;border-radius:8px 8px 4px 4px;display:flex;align-items:flex-end;overflow:hidden}.month-bar{width:100%;min-height:2px;background:var(--green);border-radius:7px 7px 0 0}.month-name{font-size:9px;color:var(--muted);font-weight:800;text-transform:uppercase}.channel-wrap{display:grid;place-items:center;margin:12px 0 18px}.channel-donut{width:170px;height:170px;border-radius:50%;position:relative}.channel-donut:after{content:'';position:absolute;inset:32px;border-radius:50%;background:#fff}.channel-center{position:absolute;z-index:2;inset:0;display:grid;place-content:center;text-align:center}.channel-center strong{font-size:25px}.channel-center span{font-size:10px;color:var(--muted)}.channel-legend{display:grid;gap:9px}.channel-row{display:grid;grid-template-columns:auto 1fr auto;gap:8px;align-items:center;font-size:12px}.channel-dot{width:10px;height:10px;border-radius:3px}.channel-row span:nth-child(2){color:var(--muted)}.stats-note{margin-top:14px;padding:11px 12px;background:#f6faf8;border:1px solid var(--line);border-radius:12px;color:var(--muted);font-size:11px;line-height:1.5}.inprogress-badge{margin-left:5px}.selection-actions{display:grid;grid-template-columns:repeat(4,minmax(0,1fr))}.selection-book{background:#eaf8f3!important;color:var(--green)!important;border:1px solid #cfe5dc!important}
@media(max-width:900px){.stats-kpis{grid-template-columns:repeat(2,minmax(0,1fr))}.stats-grid{grid-template-columns:1fr}}
@media(max-width:760px){.stats-toolbar{align-items:stretch;flex-direction:column}.stats-year{width:100%}.stats-kpis{gap:8px}.stats-kpi{padding:12px}.stats-kpi strong{font-size:21px}.monthly-chart{height:220px;gap:4px;overflow-x:auto}.month-track{height:160px;min-width:18px}.month-value{font-size:8px}.month-name{font-size:8px}.selection-actions{grid-template-columns:repeat(2,minmax(0,1fr))!important}.channel-donut{width:150px;height:150px}}
</style>`)}

function ensureModal(){if(q('#bookingDetailModal'))return;document.body.insertAdjacentHTML('beforeend',`<div class="admin-modal" id="bookingDetailModal" aria-hidden="true"><div class="admin-modal-backdrop" data-close-modal></div><div class="admin-modal-card" role="dialog" aria-modal="true" aria-labelledby="bookingDetailTitle"><button class="admin-modal-close" type="button" aria-label="Chiudi" data-close-modal>×</button><div id="bookingDetailBody"></div></div></div>`);qa('[data-close-modal]').forEach(x=>x.onclick=closeBookingModal)}
function closeBookingModal(){const m=q('#bookingDetailModal');if(!m)return;m.classList.remove('open');m.setAttribute('aria-hidden','true');document.body.classList.remove('modal-open')}
function openBookingModal(e){if(!e)return;ensureModal();const r=requestForEntry(e),source=sourceLabel(e),nights=Math.max(1,Math.round((parseDate(e.end_date)-parseDate(e.start_date))/DAY)),title=e.guest_name||r?.guest_name||'Ospite',today=dateKey(new Date()),inProgress=e.start_date<=today&&today<e.end_date;q('#bookingDetailBody').innerHTML=`<div class="detail-kicker">${inProgress?'Soggiorno in corso':'Dettagli soggiorno'}</div><h2 id="bookingDetailTitle">${safe(title)}</h2><div class="detail-dates"><div><span>CHECK-IN</span><strong>${fmt(e.start_date)}</strong></div><div class="detail-arrow">→</div><div><span>CHECK-OUT</span><strong>${fmt(e.end_date)}</strong></div></div><div class="detail-nights">${inProgress?'<span class="badge booked">In corso</span> · ':''}${nights} ${nights===1?'notte':'notti'} · ${safe(source)}</div>${r?`<div class="detail-info"><b>${r.guests} ospiti</b><span>Codice ${safe(r.request_code)}</span>${r.guest_email?`<span>${safe(r.guest_email)}</span>`:''}${r.guest_phone?`<span>${safe(r.guest_phone)}</span>`:''}</div>${contactLinks(r)}`:(e.note?`<div class="detail-info"><span>${safe(e.note)}</span></div>`:'')}<div class="detail-actions"><button class="btn primary" type="button" id="detailOpenFuture">Apri prenotazioni future</button></div>`;q('#detailOpenFuture').onclick=()=>{closeBookingModal();goSection('futureSec')};const m=q('#bookingDetailModal');m.classList.add('open');m.setAttribute('aria-hidden','false');document.body.classList.add('modal-open')}

function ensureDashboard(){if(q('#adminDashboard'))return;const head=q('.admin-head');if(!head)return;head.insertAdjacentHTML('afterend',`<section id="adminDashboard" class="admin-dashboard"><div class="dash-grid"><button class="dash-card dash-clickable" id="dashCheckinCard" type="button"><span class="dash-label">Prossimo check-in</span><strong class="dash-value" id="dashCheckin">—</strong><span class="dash-sub" id="dashCheckinSub">Nessuno</span><span class="dash-open">Dettagli</span></button><button class="dash-card dash-clickable" id="dashCheckoutCard" type="button"><span class="dash-label">Prossimo check-out</span><strong class="dash-value" id="dashCheckout">—</strong><span class="dash-sub" id="dashCheckoutSub">Nessuno</span><span class="dash-open">Dettagli</span></button><button class="dash-card dash-clickable" id="dashRequestsCard" type="button"><span class="dash-label">Richieste nuove</span><strong class="dash-value" id="dashRequests">0</strong><span class="dash-sub">Apri richieste</span><span class="dash-open">Apri</span></button><button class="dash-card dash-clickable" id="dashFutureCard" type="button"><span class="dash-label">Prenotazioni future</span><strong class="dash-value" id="dashFuture">0</strong><span class="dash-sub">Totali</span><span class="dash-open">Apri</span></button><button class="dash-card dash-clickable" id="dashSyncCard" type="button"><span class="dash-label">Sincronizzazione</span><strong class="dash-value" id="dashSync">—</strong><span class="dash-sub" id="dashSyncSub">Calendari OTA</span><span class="dash-open">Apri</span></button></div><div class="quick-actions"><button class="btn" data-quick="booking">Nuova prenotazione</button><button class="btn" data-quick="block">Blocca date</button><button class="btn" data-quick="requests">Richieste</button><button class="btn" data-quick="price">Imposta tariffa</button></div></section>`);q('[data-quick="booking"]').onclick=()=>goForm('bookingPanel');q('[data-quick="block"]').onclick=()=>goForm('blockPanel');q('[data-quick="requests"]').onclick=()=>goSection('requestsSec');q('[data-quick="price"]').onclick=()=>goSection('pricesSec');q('#dashCheckinCard').onclick=()=>openBookingModal(nextCheckinEntry);q('#dashCheckoutCard').onclick=()=>openBookingModal(nextCheckoutEntry);q('#dashRequestsCard').onclick=()=>goSection('requestsSec');q('#dashFutureCard').onclick=()=>goSection('futureSec');q('#dashSyncCard').onclick=()=>goSection('syncSec')}
function renderDashboard(){ensureDashboard();if(typeof entries==='undefined')return;const today=dateKey(new Date()),future=entries.filter(e=>e.status==='booked'&&e.end_date>today).sort((a,b)=>a.start_date.localeCompare(b.start_date));const current=future.find(e=>e.start_date<=today&&today<e.end_date)||null;nextCheckinEntry=future.find(e=>e.start_date>=today)||current||future[0]||null;nextCheckoutEntry=current||future[0]||null;q('#dashFuture').textContent=future.length;q('#dashRequests').textContent=(requests||[]).filter(r=>r.status==='new').length;if(nextCheckinEntry){q('#dashCheckin').textContent=fmt(nextCheckinEntry.start_date);q('#dashCheckinSub').textContent=nextCheckinEntry.guest_name||requestForEntry(nextCheckinEntry)?.guest_name||'Ospite';q('#dashCheckinCard').disabled=false}else{q('#dashCheckin').textContent='—';q('#dashCheckinSub').textContent='Nessuno';q('#dashCheckinCard').disabled=true}if(nextCheckoutEntry){q('#dashCheckout').textContent=fmt(nextCheckoutEntry.end_date);q('#dashCheckoutSub').textContent=(current?'In corso · ':'')+(nextCheckoutEntry.guest_name||requestForEntry(nextCheckoutEntry)?.guest_name||'Ospite');q('#dashCheckoutCard').disabled=false}else{q('#dashCheckout').textContent='—';q('#dashCheckoutSub').textContent='Nessuno';q('#dashCheckoutCard').disabled=true}const active=(feeds||[]).filter(f=>f.is_active!==false),errors=active.filter(f=>f.last_error);q('#dashSync').textContent=!active.length?'Nessuno':errors.length?`${errors.length} errore${errors.length===1?'':'i'}`:'OK';q('#dashSyncSub').textContent=!active.length?'Nessun feed OTA':active.length===1?'1 calendario collegato':`${active.length} calendari collegati`}

function ensureFutureFilters(){const sec=q('#futureSec .card');if(!sec)return;sec.querySelector(':scope > p.muted')?.remove();const stats=sec.querySelector(':scope > .stats');if(!stats||stats.classList.contains('future-filters'))return;stats.className='stats future-filters';stats.innerHTML=`<button class="stat filter-stat active" data-future-filter="all"><b id="futureCount">0</b><span>Tutte</span></button><button class="stat filter-stat" data-future-filter="direct"><b id="futureDirectCount">0</b><span>Dirette</span></button><button class="stat filter-stat" data-future-filter="booking"><b id="futureBookingCount">0</b><span>Booking</span></button><button class="stat filter-stat" data-future-filter="airbnb"><b id="futureAirbnbCount">0</b><span>Airbnb</span></button>`;qa('[data-future-filter]').forEach(b=>b.onclick=()=>{futureFilter=b.dataset.futureFilter;qa('[data-future-filter]').forEach(x=>x.classList.toggle('active',x===b));enhancedFuture()})}
function bookingDateBlock(e,nights){return `<div class="booking-dates"><div><span>CHECK-IN</span><strong>${fmt(e.start_date)}</strong></div><div class="booking-date-mid"><span>${nights} ${nights===1?'notte':'notti'}</span><b>→</b></div><div><span>CHECK-OUT</span><strong>${fmt(e.end_date)}</strong></div></div>`}
function enhancedFuture(){const list=$('futureBookingsList');if(!list)return;ensureFutureFilters();const today=dateKey(new Date()),all=entries.filter(e=>e.status==='booked'&&e.end_date>today).sort((a,b)=>a.start_date.localeCompare(b.start_date)||a.end_date.localeCompare(b.end_date));const counts={all:all.length,direct:all.filter(e=>platformFor(e)==='direct'&&!e.external_feed_id).length,booking:all.filter(e=>platformFor(e)==='booking').length,airbnb:all.filter(e=>platformFor(e)==='airbnb').length};$('futureCount').textContent=counts.all;$('futureDirectCount').textContent=counts.direct;$('futureBookingCount').textContent=counts.booking;$('futureAirbnbCount').textContent=counts.airbnb;const future=futureFilter==='all'?all:all.filter(e=>futureFilter==='direct'?(platformFor(e)==='direct'&&!e.external_feed_id):platformFor(e)===futureFilter);list.innerHTML='';if(!future.length){list.innerHTML='<div class="empty">Nessuna prenotazione in questa categoria.</div>';renderDashboard();return}future.forEach(e=>{const r=requestForEntry(e),d=document.createElement('article'),platform=platformFor(e),source=sourceLabel(e),nights=Math.max(1,Math.round((parseDate(e.end_date)-parseDate(e.start_date))/DAY)),title=e.guest_name||r?.guest_name||'Ospite',inProgress=e.start_date<=today&&today<e.end_date;d.className=`future-booking-card source-${platform==='booking'?'booking':platform==='airbnb'?'airbnb':'direct'}${inProgress?' is-current':''}`;let extra='';if(r)extra=`<div class="future-meta"><span>${r.guests} ospiti</span><span>Codice ${safe(r.request_code)}</span>${Number.isFinite(Number(r.estimated_total))?`<span>€ ${Number(r.estimated_total).toFixed(0)} indicativi</span>`:''}</div>${contactLinks(r)}`;else if(e.note)extra=`<div class="future-meta"><span>${safe(e.note)}</span></div>`;else if(e.external_feed_id)extra='<div class="future-meta"><span>Dettagli ospite non disponibili nel feed iCal.</span></div>';d.innerHTML=`${bookingDateBlock(e,nights)}<div class="future-booking-body"><div class="future-title-row"><div><span class="badge ${platform==='direct'&&!e.external_feed_id?'booked':'sync'}">${safe(source)}</span>${inProgress?'<span class="badge booked inprogress-badge">In corso</span>':''}<h3>${safe(title)}</h3></div></div>${extra}<div class="row-actions"></div></div>`;const a=d.querySelector('.row-actions');if(platform==='direct'&&!e.external_feed_id){const edit=document.createElement('button');edit.className='btn light small';edit.textContent='Modifica';edit.onclick=()=>editEntry(e);const cancel=document.createElement('button');cancel.className='btn danger small';cancel.textContent='Annulla';cancel.onclick=()=>cancelDirectBooking(e,r);a.append(edit,cancel)}else{const detail=document.createElement('button');detail.className='btn light small';detail.textContent='Dettagli';detail.onclick=()=>openBookingModal(e);a.appendChild(detail)}list.appendChild(d)});renderDashboard()}

function ensureCalendarActions(){const cal=$('adminCalendar');if(!cal)return;const card=cal.closest('.card');if(!card)return;const old=q('#calendarSelectionBar');if(old&&!q('#selectionBook'))old.remove();if(q('#calendarSelectionBar'))return;const hint=card.querySelector('.hint');if(hint)hint.textContent='Tocca una data per selezionarla; tocca una seconda data per creare un intervallo.';cal.insertAdjacentHTML('afterend',`<div id="calendarSelectionBar" class="calendar-selection"><div><span class="selection-label">Selezione</span><strong id="selectionText">Nessuna data selezionata</strong></div><div class="selection-actions"><button type="button" class="btn orange small" id="selectionBlock" disabled>Blocca</button><button type="button" class="btn light small selection-book" id="selectionBook" disabled>Nuova prenotazione</button><button type="button" class="btn primary small" id="selectionPrice" disabled>Imposta prezzo</button><button type="button" class="btn light small" id="selectionClear" disabled>Annulla</button></div></div>`);$('selectionBlock').onclick=()=>useSelection('block');$('selectionBook').onclick=()=>useSelection('booking');$('selectionPrice').onclick=()=>useSelection('price');$('selectionClear').onclick=clearSelection}
function selectionBounds(){if(!rangeStart)return null;const a=rangeStart,b=rangeEnd||rangeStart;return a<=b?{start:a,end:b}:{start:b,end:a}}
function updateSelectionUI(){ensureCalendarActions();const s=selectionBounds(),text=$('selectionText'),buttons=[$('selectionBlock'),$('selectionBook'),$('selectionPrice'),$('selectionClear')].filter(Boolean);buttons.forEach(b=>b.disabled=!s);if(!s){if(text)text.textContent='Nessuna data selezionata';return}if(text)text.textContent=s.start===s.end?fmt(s.start):`${fmt(s.start)} → ${fmt(s.end)}`}
function clearSelection(){rangeStart=null;rangeEnd=null;calendarSelectionStart=null;renderCalendar();updateSelectionUI()}
function useSelection(type){const s=selectionBounds();if(!s)return;if(type==='block'){resetBlock();$('blockStart').value=s.start;$('blockEnd').value=s.end;const form=$('blockPanel');if(!form)return;form.requestSubmit()}else if(type==='booking'){$('bookStart').value=s.start;$('bookEnd').value=plusDays(s.end,1);goForm('bookingPanel')}else{$('priceStart').value=s.start;$('priceEnd').value=s.end;goSection('pricesSec');setTimeout(()=>$('nightlyPrice')?.focus(),120)}}
function selectCalendarDate(k){if(!rangeStart||(rangeStart&&rangeEnd)){rangeStart=k;rangeEnd=null}else rangeEnd=k;renderCalendar();updateSelectionUI()}
function highlightRange(){const s=selectionBounds(),buttons=qa('#adminCalendar .day');buttons.forEach(b=>b.classList.remove('sel-range','sel-start','sel-end'));if(!s||!buttons.length)return;const first=new Date(view.getFullYear(),view.getMonth(),1),offset=(first.getDay()+6)%7,gridStart=new Date(first.getTime()-offset*DAY);buttons.forEach((b,i)=>{const k=dateKey(new Date(gridStart.getTime()+i*DAY));if(k>=s.start&&k<=s.end)b.classList.add('sel-range');if(k===s.start)b.classList.add('sel-start');if(k===s.end)b.classList.add('sel-end')})}

async function cancelConfirmedDirectRequest(r,e){if(!e)return;if(!confirm(`Annullare la richiesta ${r.request_code}? La prenotazione verrà cancellata e le date torneranno disponibili.`))return;const {error}=await sb.rpc('cancel_direct_booking',{p_entry_id:e.id});if(error)return msg($('requestMsg'),'Impossibile annullare: '+error.message,'error');msg($('requestMsg'),`Richiesta ${r.request_code} annullata e date liberate.`,'ok');await Promise.all([loadRequests(),loadEntries()]);renderAll()}
function enhancedRequests(){const list=$('requestsList');if(!list)return;const active=requests.filter(r=>r.status==='new'||r.status==='waiting').length;$('requestCountBadge').textContent=active?`(${active})`:'';$('reqNewCount').textContent=requests.filter(r=>r.status==='new').length;$('reqWaitingCount').textContent=requests.filter(r=>r.status==='waiting').length;$('reqConfirmedCount').textContent=requests.filter(r=>r.status==='confirmed').length;list.innerHTML='';if(!requests.length){list.innerHTML='<div class="empty">Nessuna richiesta dal sito.</div>';renderDashboard();return}requests.forEach(r=>{const d=document.createElement('div'),when=new Intl.DateTimeFormat('it-IT',{dateStyle:'short',timeStyle:'short'}).format(new Date(r.created_at)),total=Number(r.estimated_total).toFixed(0);d.className=`item admin-rich request-${r.status}`;d.innerHTML=`<div><span class="badge ${r.status==='confirmed'?'booked':(r.status==='rejected'||r.status==='cancelled')?'blocked':'sync'}">${safe(requestStatusLabel(r.status))}</span><strong>Richiesta ${safe(r.request_code)} · ${safe(r.guest_name||'Ospite')}</strong><div class="meta">${fmt(r.check_in)} → ${fmt(r.check_out)} · ${r.guests} ospiti · € ${total} indicativi · ricevuta ${safe(when)}<br>Email: ${safe(r.guest_email||'—')}${r.guest_phone?` · Tel/WhatsApp: ${safe(r.guest_phone)}`:''}</div>${contactLinks(r)}</div><div class="row-actions"></div>`;const actions=d.querySelector('.row-actions');if(r.status!=='confirmed'&&r.status!=='cancelled'){if(r.status==='new'){const b=document.createElement('button');b.className='btn light small';b.textContent='In attesa';b.onclick=()=>setRequestStatus(r.id,'waiting');actions.appendChild(b)}if(r.status!=='rejected'){const rej=document.createElement('button');rej.className='btn danger small';rej.textContent='Rifiuta';rej.onclick=()=>rejectRequest(r);const conf=document.createElement('button');conf.className='btn primary small';conf.textContent='Conferma';conf.onclick=()=>confirmRequest(r);actions.append(rej,conf)}}else if(r.status==='confirmed'){const e=entries.find(x=>Number(x.id)===Number(r.confirmed_entry_id));if(e&&platformFor(e)==='direct'&&!e.external_feed_id){const cancel=document.createElement('button');cancel.className='btn danger small';cancel.textContent='Annulla e libera date';cancel.onclick=()=>cancelConfirmedDirectRequest(r,e);actions.appendChild(cancel)}else{const done=document.createElement('span');done.className='muted';done.textContent='Calendario bloccato';actions.appendChild(done)}}else{const done=document.createElement('span');done.className='muted';done.textContent='Richiesta chiusa';actions.appendChild(done)}list.appendChild(d)});renderDashboard()}

function ensureStatsSection(){if(q('#statsSec'))return;const tabs=q('.navtabs'),futureTab=q('.navtab[data-section="futureSec"]');if(!tabs||!futureTab)return;futureTab.insertAdjacentHTML('afterend','<button class="navtab" data-section="statsSec">Statistiche</button>');const statsTab=q('.navtab[data-section="statsSec"]');statsTab.onclick=()=>activateSection('statsSec');const anchor=q('#requestsSec')||q('#pricesSec')||q('#syncSec');anchor.insertAdjacentHTML('beforebegin',`<section id="statsSec" class="section"><div class="stats-toolbar"><div><div class="muted">Andamento della struttura</div><h1 style="font-size:32px;margin:0">Statistiche</h1></div><div class="stats-year"><label for="statsYearSelect">Anno</label><select id="statsYearSelect"></select></div></div><div class="stats-kpis"><div class="stats-kpi"><span>Occupazione</span><strong id="statOccupancy">0%</strong><small id="statOccupancySub">0 notti prenotate</small></div><div class="stats-kpi"><span>Prenotazioni</span><strong id="statBookings">0</strong><small id="statBookingsSub">nell'anno</small></div><div class="stats-kpi"><span>Soggiorno medio</span><strong id="statAvgStay">0</strong><small>notti per prenotazione</small></div><div class="stats-kpi"><span>Notti bloccate</span><strong id="statBlocked">0</strong><small>non vendibili</small></div></div><div class="stats-grid"><div class="stats-card"><h2>Occupazione mese per mese</h2><div class="stats-card-sub">Percentuale di notti prenotate sulle notti vendibili del mese.</div><div id="monthlyChart" class="monthly-chart"></div></div><div class="stats-card"><h2>Canali di prenotazione</h2><div class="stats-card-sub">Ripartizione delle notti prenotate.</div><div id="channelChart"></div></div></div><div class="stats-note">Le statistiche utilizzano le prenotazioni e i blocchi presenti nel calendario. I feed iCal di Booking e Airbnb non comunicano gli importi economici, quindi qui non vengono mostrati ricavi OTA non verificabili.</div></section>`);q('#statsYearSelect').onchange=e=>{statsYear=Number(e.target.value);renderStats()}}
function activateSection(id){qa('.navtab').forEach(x=>x.classList.toggle('active',x.dataset.section===id));qa('.section').forEach(s=>s.classList.toggle('active',s.id===id));if(id==='statsSec')renderStats()}
function overlapNights(e,start,end){const a=Math.max(parseDate(e.start_date).getTime(),start.getTime()),b=Math.min(parseDate(e.end_date).getTime(),end.getTime());return Math.max(0,Math.round((b-a)/DAY))}
function renderStats(){ensureStatsSection();const sel=q('#statsYearSelect');if(!sel)return;const years=new Set([new Date().getFullYear()]);(entries||[]).forEach(e=>{years.add(parseDate(e.start_date).getFullYear());years.add(parseDate(e.end_date).getFullYear())});const ys=[...years].sort((a,b)=>b-a);if(!ys.includes(statsYear))statsYear=ys[0];const previous=sel.value;sel.innerHTML=ys.map(y=>`<option value="${y}"${y===statsYear?' selected':''}>${y}</option>`).join('');if(previous&&ys.includes(Number(previous)))statsYear=Number(previous);sel.value=String(statsYear);const yStart=new Date(statsYear,0,1),yEnd=new Date(statsYear+1,0,1),bookings=entries.filter(e=>e.status==='booked'&&overlapNights(e,yStart,yEnd)>0),blockedEntries=entries.filter(e=>e.status==='blocked'&&overlapNights(e,yStart,yEnd)>0),bookedNights=bookings.reduce((n,e)=>n+overlapNights(e,yStart,yEnd),0),blockedNights=blockedEntries.reduce((n,e)=>n+overlapNights(e,yStart,yEnd),0),yearDays=Math.round((yEnd-yStart)/DAY),sellable=Math.max(1,yearDays-blockedNights),occupancy=Math.min(100,Math.round(bookedNights/sellable*100)),avg=bookings.length?(bookedNights/bookings.length):0;q('#statOccupancy').textContent=`${occupancy}%`;q('#statOccupancySub').textContent=`${bookedNights} notti prenotate su ${sellable} vendibili`;q('#statBookings').textContent=bookings.length;q('#statBookingsSub').textContent=bookings.length===1?'1 soggiorno nell’anno':`${bookings.length} soggiorni nell’anno`;q('#statAvgStay').textContent=avg?avg.toFixed(1):'0';q('#statBlocked').textContent=blockedNights;renderMonthlyStats(statsYear);renderChannelStats(bookings,yStart,yEnd)}
function renderMonthlyStats(year){const names=['Gen','Feb','Mar','Apr','Mag','Giu','Lug','Ago','Set','Ott','Nov','Dic'];const chart=q('#monthlyChart');chart.innerHTML='';for(let m=0;m<12;m++){const start=new Date(year,m,1),end=new Date(year,m+1,1),days=Math.round((end-start)/DAY),booked=entries.filter(e=>e.status==='booked').reduce((n,e)=>n+overlapNights(e,start,end),0),blocked=entries.filter(e=>e.status==='blocked').reduce((n,e)=>n+overlapNights(e,start,end),0),sellable=Math.max(1,days-blocked),pct=Math.min(100,Math.round(booked/sellable*100)),col=document.createElement('div');col.className='month-col';col.title=`${names[m]} ${year}: ${booked} notti prenotate, ${blocked} bloccate, ${pct}% occupazione`;col.innerHTML=`<div class="month-value">${pct}%</div><div class="month-track"><div class="month-bar" style="height:${Math.max(pct,1)}%"></div></div><div class="month-name">${names[m]}</div>`;chart.appendChild(col)}}
function renderChannelStats(bookings,start,end){const colors={booking:'#0b6edb',airbnb:'#e56b6f',direct:'#2f6f62',other:'#91a39d'},labels={booking:'Booking',airbnb:'Airbnb',direct:'Dirette',other:'Altro'};const values={booking:0,airbnb:0,direct:0,other:0};bookings.forEach(e=>{const p=platformFor(e),k=['booking','airbnb','direct'].includes(p)?p:'other';values[k]+=overlapNights(e,start,end)});const total=Object.values(values).reduce((a,b)=>a+b,0);let cursor=0,parts=[];['booking','airbnb','direct','other'].forEach(k=>{const pct=total?values[k]/total*100:0;if(pct>0){parts.push(`${colors[k]} ${cursor}% ${cursor+pct}%`);cursor+=pct}});const bg=parts.length?`conic-gradient(${parts.join(',')})`:'#eef4f2';q('#channelChart').innerHTML=`<div class="channel-wrap"><div class="channel-donut" style="background:${bg}"><div class="channel-center"><strong>${total}</strong><span>notti</span></div></div></div><div class="channel-legend">${['booking','airbnb','direct','other'].map(k=>{const pct=total?Math.round(values[k]/total*100):0;return `<div class="channel-row"><i class="channel-dot" style="background:${colors[k]}"></i><span>${labels[k]}</span><b>${values[k]} · ${pct}%</b></div>`}).join('')}</div>`}

function markRichItems(){qa('.item').forEach(i=>i.classList.add('admin-rich'))}
function enhanceFeeds(){qa('#feedsList .item').forEach((d,i)=>{d.classList.add('admin-rich');const f=feeds[i];if(!f)return;const line=d.querySelector('.statusline');if(line&&!d.querySelector('.sync-health'))line.insertAdjacentHTML('afterend',`<span class="sync-health ${f.last_error?'error':'ok'}">${f.last_error?'⚠ Errore':'✓ Sincronizzato'}</span>`)})}
function ensureSyncOrder(){const col=q('#syncSec .grid > div:first-child');if(!col)return;const cards=[...col.children].filter(x=>x.classList?.contains('card')),linked=cards.find(x=>x.querySelector('h2')?.textContent.trim()==='Calendari collegati'),importCard=cards.find(x=>x.querySelector('h2')?.textContent.trim()==='Importa calendari OTA');if(linked&&importCard&&linked.nextElementSibling!==importCard)col.insertBefore(linked,importCard)}
function afterRender(){injectExtraStyles();ensureDashboard();ensureFutureFilters();ensureCalendarActions();ensureStatsSection();ensureSyncOrder();renderDashboard();renderStats();markRichItems();highlightRange();updateSelectionUI();enhanceFeeds()}

const oldRenderAll=renderAll;renderAll=function(){oldRenderAll();enhancedFuture();enhancedRequests();afterRender()};
const oldRenderCalendar=renderCalendar;renderCalendar=function(){oldRenderCalendar();ensureCalendarActions();highlightRange()};
selectBlockDate=selectCalendarDate;
renderFutureBookings=enhancedFuture;renderRequests=enhancedRequests;
const oldRenderFeeds=renderFeeds;renderFeeds=function(){oldRenderFeeds();enhanceFeeds();ensureSyncOrder();renderDashboard()};
injectExtraStyles();ensureDashboard();ensureModal();ensureFutureFilters();ensureCalendarActions();ensureStatsSection();ensureSyncOrder();setTimeout(()=>{if($('adminView')?.style.display!=='none'){enhancedFuture();enhancedRequests();afterRender()}},300);
document.addEventListener('keydown',e=>{if(e.key==='Escape')closeBookingModal()});
const hs=document.createElement('script');hs.src='admin-stats-history.js?v=20260825-0945';hs.defer=true;document.head.appendChild(hs);
})();