(()=>{
'use strict';
const q=s=>document.querySelector(s),qa=s=>[...document.querySelectorAll(s)];
const safe=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const phoneHref=p=>p?`https://wa.me/${String(p).replace(/\D/g,'')}`:null;
let futureFilter='all',rangeStart=null,rangeEnd=null,nextCheckinEntry=null;

function goSection(id){const tab=q(`.navtab[data-section="${id}"]`);if(tab){tab.click();setTimeout(()=>q(`#${id}`)?.scrollIntoView({behavior:'smooth',block:'start'}),50)}}
function goForm(form){goSection('calendarSec');setTimeout(()=>{q(`[data-form="${form}"]`)?.click();q(`#${form}`)?.scrollIntoView({behavior:'smooth',block:'start'})},100)}
function platformFor(e){if(e.source==='booking'||e.source==='airbnb'||e.source==='direct')return e.source;const f=(feeds||[]).find(x=>Number(x.id)===Number(e.external_feed_id));return f?.provider||e.source||'other'}
function sourceLabel(e){return ({direct:'Diretta',booking:'Booking.com',airbnb:'Airbnb',manual:'Manuale',other:'Altro'})[platformFor(e)]||platformFor(e)}
function requestForEntry(e){return (requests||[]).find(x=>Number(x.confirmed_entry_id)===Number(e.id))}
function contactLinks(r){const parts=[];if(r?.guest_phone){const wa=phoneHref(r.guest_phone);if(wa)parts.push(`<a class="contact-link wa" target="_blank" rel="noopener" href="${wa}">WhatsApp</a>`)}if(r?.guest_email)parts.push(`<a class="contact-link mail" href="mailto:${encodeURIComponent(r.guest_email)}">Email</a>`);return parts.length?`<div class="contact-actions">${parts.join('')}</div>`:''}

function ensureModal(){if(q('#bookingDetailModal'))return;document.body.insertAdjacentHTML('beforeend',`<div class="admin-modal" id="bookingDetailModal" aria-hidden="true"><div class="admin-modal-backdrop" data-close-modal></div><div class="admin-modal-card" role="dialog" aria-modal="true" aria-labelledby="bookingDetailTitle"><button class="admin-modal-close" type="button" aria-label="Chiudi" data-close-modal>×</button><div id="bookingDetailBody"></div></div></div>`);qa('[data-close-modal]').forEach(x=>x.onclick=closeBookingModal)}
function closeBookingModal(){const m=q('#bookingDetailModal');if(!m)return;m.classList.remove('open');m.setAttribute('aria-hidden','true');document.body.classList.remove('modal-open')}
function openBookingModal(e){if(!e)return;ensureModal();const r=requestForEntry(e),source=sourceLabel(e),nights=Math.max(1,Math.round((parseDate(e.end_date)-parseDate(e.start_date))/DAY)),title=e.guest_name||r?.guest_name||'Ospite';q('#bookingDetailBody').innerHTML=`<div class="detail-kicker">Prossima prenotazione</div><h2 id="bookingDetailTitle">${safe(title)}</h2><div class="detail-dates"><div><span>CHECK-IN</span><strong>${fmt(e.start_date)}</strong></div><div class="detail-arrow">→</div><div><span>CHECK-OUT</span><strong>${fmt(e.end_date)}</strong></div></div><div class="detail-nights">${nights} ${nights===1?'notte':'notti'} · ${safe(source)}</div>${r?`<div class="detail-info"><b>${r.guests} ospiti</b><span>Codice ${safe(r.request_code)}</span>${r.guest_email?`<span>${safe(r.guest_email)}</span>`:''}${r.guest_phone?`<span>${safe(r.guest_phone)}</span>`:''}</div>${contactLinks(r)}`:(e.note?`<div class="detail-info"><span>${safe(e.note)}</span></div>`:'')}<div class="detail-actions"><button class="btn primary" type="button" id="detailOpenFuture">Apri prenotazioni future</button></div>`;q('#detailOpenFuture').onclick=()=>{closeBookingModal();goSection('futureSec')};const m=q('#bookingDetailModal');m.classList.add('open');m.setAttribute('aria-hidden','false');document.body.classList.add('modal-open')}

function ensureDashboard(){if(q('#adminDashboard'))return;const head=q('.admin-head');if(!head)return;head.insertAdjacentHTML('afterend',`<section id="adminDashboard" class="admin-dashboard"><div class="dash-grid"><button class="dash-card dash-clickable" id="dashCheckinCard" type="button"><span class="dash-label">Prossimo check-in</span><strong class="dash-value" id="dashCheckin">—</strong><span class="dash-sub" id="dashCheckinSub">Nessuno</span><span class="dash-open">Dettagli</span></button><div class="dash-card"><span class="dash-label">Prossimo check-out</span><strong class="dash-value" id="dashCheckout">—</strong><span class="dash-sub" id="dashCheckoutSub">Nessuno</span></div><div class="dash-card"><span class="dash-label">Richieste nuove</span><strong class="dash-value" id="dashRequests">0</strong><span class="dash-sub">Da gestire</span></div><div class="dash-card"><span class="dash-label">Prenotazioni future</span><strong class="dash-value" id="dashFuture">0</strong><span class="dash-sub">Totali</span></div><div class="dash-card"><span class="dash-label">Sincronizzazione</span><strong class="dash-value" id="dashSync">—</strong><span class="dash-sub" id="dashSyncSub">Calendari OTA</span></div></div><div class="quick-actions"><button class="btn" data-quick="booking">Nuova prenotazione</button><button class="btn" data-quick="block">Blocca date</button><button class="btn" data-quick="requests">Richieste</button><button class="btn" data-quick="price">Imposta tariffa</button></div></section>`);q('[data-quick="booking"]').onclick=()=>goForm('bookingPanel');q('[data-quick="block"]').onclick=()=>goForm('blockPanel');q('[data-quick="requests"]').onclick=()=>goSection('requestsSec');q('[data-quick="price"]').onclick=()=>goSection('pricesSec');q('#dashCheckinCard').onclick=()=>openBookingModal(nextCheckinEntry)}
function renderDashboard(){ensureDashboard();if(typeof entries==='undefined')return;const today=dateKey(new Date()),future=entries.filter(e=>e.status==='booked'&&e.end_date>today).sort((a,b)=>a.start_date.localeCompare(b.start_date));nextCheckinEntry=future.find(e=>e.start_date>=today)||future[0]||null;const nextOut=future.find(e=>e.end_date>=today)||future[0]||null;q('#dashFuture').textContent=future.length;q('#dashRequests').textContent=(requests||[]).filter(r=>r.status==='new').length;if(nextCheckinEntry){q('#dashCheckin').textContent=fmt(nextCheckinEntry.start_date);q('#dashCheckinSub').textContent=nextCheckinEntry.guest_name||requestForEntry(nextCheckinEntry)?.guest_name||'Ospite';q('#dashCheckinCard').disabled=false}else{q('#dashCheckin').textContent='—';q('#dashCheckinSub').textContent='Nessuno';q('#dashCheckinCard').disabled=true}if(nextOut){q('#dashCheckout').textContent=fmt(nextOut.end_date);q('#dashCheckoutSub').textContent=nextOut.guest_name||requestForEntry(nextOut)?.guest_name||'Ospite'}else{q('#dashCheckout').textContent='—';q('#dashCheckoutSub').textContent='Nessuno'}const active=(feeds||[]).filter(f=>f.is_active!==false),errors=active.filter(f=>f.last_error);q('#dashSync').textContent=!active.length?'Nessuno':errors.length?`${errors.length} errore${errors.length===1?'':'i'}`:'OK';q('#dashSyncSub').textContent=active.length?`${active.length} calendario${active.length===1?'':'i'} collegato${active.length===1?'':'i'}`:'Nessun feed OTA'}

function ensureFutureFilters(){const sec=q('#futureSec .card');if(!sec)return;const intro=sec.querySelector(':scope > p.muted');if(intro)intro.remove();let stats=sec.querySelector(':scope > .stats');if(!stats)return;if(!stats.classList.contains('future-filters')){stats.className='stats future-filters';stats.innerHTML=`<button class="stat filter-stat active" data-future-filter="all"><b id="futureCount">0</b><span>Tutte</span></button><button class="stat filter-stat" data-future-filter="direct"><b id="futureDirectCount">0</b><span>Dirette</span></button><button class="stat filter-stat" data-future-filter="booking"><b id="futureBookingCount">0</b><span>Booking</span></button><button class="stat filter-stat" data-future-filter="airbnb"><b id="futureAirbnbCount">0</b><span>Airbnb</span></button>`;qa('[data-future-filter]').forEach(b=>b.onclick=()=>{futureFilter=b.dataset.futureFilter;qa('[data-future-filter]').forEach(x=>x.classList.toggle('active',x===b));enhancedFuture()})}}
function bookingDateBlock(e,nights){return `<div class="booking-dates"><div><span>CHECK-IN</span><strong>${fmt(e.start_date)}</strong></div><div class="booking-date-mid"><span>${nights} ${nights===1?'notte':'notti'}</span><b>→</b></div><div><span>CHECK-OUT</span><strong>${fmt(e.end_date)}</strong></div></div>`}
function enhancedFuture(){const list=$('futureBookingsList');if(!list)return;ensureFutureFilters();const today=dateKey(new Date()),all=entries.filter(e=>e.status==='booked'&&e.end_date>today).sort((a,b)=>a.start_date.localeCompare(b.start_date)||a.end_date.localeCompare(b.end_date));const counts={all:all.length,direct:all.filter(e=>platformFor(e)==='direct'&&!e.external_feed_id).length,booking:all.filter(e=>platformFor(e)==='booking').length,airbnb:all.filter(e=>platformFor(e)==='airbnb').length};$('futureCount').textContent=counts.all;$('futureDirectCount').textContent=counts.direct;$('futureBookingCount').textContent=counts.booking;$('futureAirbnbCount').textContent=counts.airbnb;const future=futureFilter==='all'?all:all.filter(e=>futureFilter==='direct'?(platformFor(e)==='direct'&&!e.external_feed_id):platformFor(e)===futureFilter);list.innerHTML='';if(!future.length){list.innerHTML='<div class="empty">Nessuna prenotazione in questa categoria.</div>';renderDashboard();return}future.forEach(e=>{const r=requestForEntry(e),d=document.createElement('article'),platform=platformFor(e),source=sourceLabel(e),nights=Math.max(1,Math.round((parseDate(e.end_date)-parseDate(e.start_date))/DAY)),title=e.guest_name||r?.guest_name||'Ospite';d.className=`future-booking-card source-${platform==='booking'?'booking':platform==='airbnb'?'airbnb':'direct'}`;let extra='';if(r)extra=`<div class="future-meta"><span>${r.guests} ospiti</span><span>Codice ${safe(r.request_code)}</span>${Number.isFinite(Number(r.estimated_total))?`<span>€ ${Number(r.estimated_total).toFixed(0)} indicativi</span>`:''}</div>${contactLinks(r)}`;else if(e.note)extra=`<div class="future-meta"><span>${safe(e.note)}</span></div>`;else if(e.external_feed_id)extra='<div class="future-meta"><span>Dettagli ospite non disponibili nel feed iCal.</span></div>';d.innerHTML=`${bookingDateBlock(e,nights)}<div class="future-booking-body"><div class="future-title-row"><div><span class="badge ${platform==='direct'&&!e.external_feed_id?'booked':'sync'}">${safe(source)}</span><h3>${safe(title)}</h3></div></div>${extra}<div class="row-actions"></div></div>`;const a=d.querySelector('.row-actions');if(platform==='direct'&&!e.external_feed_id){const edit=document.createElement('button');edit.className='btn light small';edit.textContent='Modifica';edit.onclick=()=>editEntry(e);const cancel=document.createElement('button');cancel.className='btn danger small';cancel.textContent='Annulla';cancel.onclick=()=>cancelDirectBooking(e,r);a.append(edit,cancel)}else{const detail=document.createElement('button');detail.className='btn light small';detail.textContent='Dettagli';detail.onclick=()=>openBookingModal(e);a.appendChild(detail)}list.appendChild(d)});renderDashboard()}

function ensureCalendarActions(){const cal=$('adminCalendar');if(!cal)return;const card=cal.closest('.card');if(!card||q('#calendarSelectionBar'))return;const hint=card.querySelector('.hint');if(hint)hint.textContent='Tocca una data per selezionarla; tocca una seconda data per creare un intervallo.';cal.insertAdjacentHTML('afterend',`<div id="calendarSelectionBar" class="calendar-selection"><div><span class="selection-label">Selezione</span><strong id="selectionText">Nessuna data selezionata</strong></div><div class="selection-actions"><button type="button" class="btn orange small" id="selectionBlock" disabled>Blocca</button><button type="button" class="btn primary small" id="selectionPrice" disabled>Imposta prezzo</button><button type="button" class="btn light small" id="selectionClear" disabled>Annulla</button></div></div>`);$('selectionBlock').onclick=()=>useSelection('block');$('selectionPrice').onclick=()=>useSelection('price');$('selectionClear').onclick=clearSelection}
function selectionBounds(){if(!rangeStart)return null;const a=rangeStart,b=rangeEnd||rangeStart;return a<=b?{start:a,end:b}:{start:b,end:a}}
function updateSelectionUI(){ensureCalendarActions();const s=selectionBounds(),text=$('selectionText'),buttons=[$('selectionBlock'),$('selectionPrice'),$('selectionClear')].filter(Boolean);buttons.forEach(b=>b.disabled=!s);if(!s){if(text)text.textContent='Nessuna data selezionata';return}if(text)text.textContent=s.start===s.end?fmt(s.start):`${fmt(s.start)} → ${fmt(s.end)}`}
function clearSelection(){rangeStart=null;rangeEnd=null;calendarSelectionStart=null;renderCalendar();updateSelectionUI()}
function useSelection(type){const s=selectionBounds();if(!s)return;if(type==='block'){$('blockStart').value=s.start;$('blockEnd').value=s.end;goForm('blockPanel')}else{$('priceStart').value=s.start;$('priceEnd').value=s.end;goSection('pricesSec');setTimeout(()=>$('nightlyPrice')?.focus(),120)}}
function selectCalendarDate(k){if(!rangeStart||(rangeStart&&rangeEnd)){rangeStart=k;rangeEnd=null}else{rangeEnd=k}renderCalendar();updateSelectionUI()}
function highlightRange(){const s=selectionBounds(),buttons=qa('#adminCalendar .day');buttons.forEach(b=>b.classList.remove('sel-range','sel-start','sel-end'));if(!s||!buttons.length)return;const first=new Date(view.getFullYear(),view.getMonth(),1),offset=(first.getDay()+6)%7,gridStart=new Date(first.getTime()-offset*DAY);buttons.forEach((b,i)=>{const k=dateKey(new Date(gridStart.getTime()+i*DAY));if(k>=s.start&&k<=s.end)b.classList.add('sel-range');if(k===s.start)b.classList.add('sel-start');if(k===s.end)b.classList.add('sel-end')})}

function enhancedRequests(){const list=$('requestsList');if(!list)return;const active=requests.filter(r=>r.status==='new'||r.status==='waiting').length;$('requestCountBadge').textContent=active?`(${active})`:'';$('reqNewCount').textContent=requests.filter(r=>r.status==='new').length;$('reqWaitingCount').textContent=requests.filter(r=>r.status==='waiting').length;$('reqConfirmedCount').textContent=requests.filter(r=>r.status==='confirmed').length;list.innerHTML='';if(!requests.length){list.innerHTML='<div class="empty">Nessuna richiesta dal sito.</div>';renderDashboard();return}requests.forEach(r=>{const d=document.createElement('div'),when=new Intl.DateTimeFormat('it-IT',{dateStyle:'short',timeStyle:'short'}).format(new Date(r.created_at)),total=Number(r.estimated_total).toFixed(0);d.className=`item admin-rich request-${r.status}`;d.innerHTML=`<div><span class="badge ${r.status==='confirmed'?'booked':(r.status==='rejected'||r.status==='cancelled')?'blocked':'sync'}">${safe(requestStatusLabel(r.status))}</span><strong>Richiesta ${safe(r.request_code)} · ${safe(r.guest_name||'Ospite')}</strong><div class="meta">${fmt(r.check_in)} → ${fmt(r.check_out)} · ${r.guests} ospiti · € ${total} indicativi · ricevuta ${safe(when)}<br>Email: ${safe(r.guest_email||'—')}${r.guest_phone?` · Tel/WhatsApp: ${safe(r.guest_phone)}`:''}</div>${contactLinks(r)}</div><div class="row-actions"></div>`;const actions=d.querySelector('.row-actions');if(r.status!=='confirmed'&&r.status!=='cancelled'){if(r.status==='new'){const b=document.createElement('button');b.className='btn light small';b.textContent='In attesa';b.onclick=()=>setRequestStatus(r.id,'waiting');actions.appendChild(b)}if(r.status!=='rejected'){const rej=document.createElement('button');rej.className='btn danger small';rej.textContent='Rifiuta';rej.onclick=()=>rejectRequest(r);const conf=document.createElement('button');conf.className='btn primary small';conf.textContent='Conferma';conf.onclick=()=>confirmRequest(r);actions.append(rej,conf)}}else{const done=document.createElement('span');done.className='muted';done.textContent=r.status==='confirmed'?'Calendario bloccato':'Richiesta chiusa';actions.appendChild(done)}list.appendChild(d)});renderDashboard()}
function markRichItems(){qa('.item').forEach(i=>i.classList.add('admin-rich'))}
function enhanceFeeds(){qa('#feedsList .item').forEach((d,i)=>{d.classList.add('admin-rich');const f=feeds[i];if(!f)return;const line=d.querySelector('.statusline');if(line&&!d.querySelector('.sync-health'))line.insertAdjacentHTML('afterend',`<span class="sync-health ${f.last_error?'error':'ok'}">${f.last_error?'⚠ Errore':'✓ Sincronizzato'}</span>`)})}
function afterRender(){ensureDashboard();ensureFutureFilters();ensureCalendarActions();renderDashboard();markRichItems();highlightRange();updateSelectionUI();enhanceFeeds()}

const oldRenderAll=renderAll;renderAll=function(){oldRenderAll();enhancedFuture();enhancedRequests();afterRender()};
const oldRenderCalendar=renderCalendar;renderCalendar=function(){oldRenderCalendar();ensureCalendarActions();highlightRange()};
selectBlockDate=selectCalendarDate;
renderFutureBookings=enhancedFuture;renderRequests=enhancedRequests;
const oldRenderFeeds=renderFeeds;renderFeeds=function(){oldRenderFeeds();enhanceFeeds();renderDashboard()};
ensureDashboard();ensureModal();ensureFutureFilters();ensureCalendarActions();setTimeout(()=>{if($('adminView')?.style.display!=='none'){enhancedFuture();enhancedRequests();afterRender()}},300);
document.addEventListener('keydown',e=>{if(e.key==='Escape')closeBookingModal()});
})();