
const translations={
"Prenota":"Book","La casa":"The apartment","Il tuo soggiorno":"Your stay","Scopri":"Explore",
"Casa vacanze nel centro di Reggio Calabria":"Holiday apartment in central Reggio Calabria",
"Intero appartamento fino a 8 ospiti con 3 camere, 2 bagni e cucina attrezzata. Stazione Centrale e Corso Garibaldi sono a circa 1 minuto a piedi; il Lungomare Falcomatà a circa 5 minuti.":"Entire apartment for up to 8 guests with 3 bedrooms, 2 bathrooms and an equipped kitchen. Central Station and Corso Garibaldi are about a 1-minute walk away; the Falcomatà seafront is about 5 minutes away.",
"📅 Verifica disponibilità":"📅 Check availability","🏠 Guarda la casa":"🏠 View the apartment","📅 Verifica prezzi e disponibilità":"📅 Check prices and availability","Prenotazione diretta":"Direct booking","Ospiti":"Guests","Verifica":"Check",
"Disponibilità indicativa aggiornata dalla struttura. La prenotazione è confermata solo dopo nostra conferma.":"Availability is indicative and updated by the property. Your booking is confirmed only after our confirmation.",
"Fino a 8 ospiti":"Up to 8 guests","3 camere":"3 bedrooms","2 bagni":"2 bathrooms","Cucina":"Kitchen","Climatizzazione":"Air conditioning","Centro città":"City centre",
"Verifica disponibilità":"Check availability","Consulta il calendario, seleziona le date e inviaci una richiesta. Controlleremo Booking e Airbnb prima di confermare il soggiorno.":"Check the calendar, select your dates and send a request. We will verify Booking.com and Airbnb before confirming your stay.",
"Lun":"Mon","Mar":"Tue","Mer":"Wed","Gio":"Thu","Ven":"Fri","Sab":"Sat","Dom":"Sun","Disponibile":"Available","Non disponibile":"Unavailable","Richiedi disponibilità":"Request availability","Nome e cognome *":"Full name *","Telefono / WhatsApp":"Phone / WhatsApp","Numero di ospiti":"Number of guests","Seleziona le date":"Select dates","Seleziona check-in e check-out per calcolare il totale.":"Select check-in and check-out to calculate the total.","💬 Richiedi su WhatsApp":"💬 Request via WhatsApp",
"Gli spazi di Civico 26":"Inside Civico 26","Scoprite Civico 26: tre camere, due bagni, cucina attrezzata, Wi‑Fi e spazi esterni, fino a 8 ospiti.":"Discover Civico 26: three bedrooms, two bathrooms, an equipped kitchen, Wi-Fi and outdoor spaces, for up to 8 guests.",
"Una casa nel cuore di Reggio Calabria.":"A home in the heart of Reggio Calabria.","Spazi comodi e luminosi":"Comfortable, bright spaces","Entrambi completi":"Both fully equipped","Cucina attrezzata":"Equipped kitchen","Con zona pranzo":"With dining area","Balcone e veranda":"Balcony and veranda","Piccoli spazi all'aperto":"Small outdoor spaces","Disponibile in appartamento":"Available in the apartment","Nelle camere da letto":"In the bedrooms",
"Camera Verde":"Green Room","Camera Bianca":"White Room","Camera Rossa":"Red Room","1 foto":"1 photo","2 foto":"2 photos","3 foto":"3 photos","Camera matrimoniale con scrivania":"Double bedroom with desk","Camera matrimoniale luminosa con scrivania":"Bright double bedroom with desk","Camera matrimoniale ampia con scrivania":"Spacious double bedroom with desk","Cucina attrezzata con zona pranzo":"Equipped kitchen with dining area","Bagni":"Bathrooms","Due bagni completi":"Two full bathrooms","Due piccoli spazi all'aperto":"Two small outdoor spaces",
"Nel cuore della città":"In the heart of the city","Una base comoda per vivere Reggio Calabria a piedi e raggiungere facilmente lo Stretto e la Costa Viola.":"A convenient base for exploring Reggio Calabria on foot and reaching the Strait and Costa Viola.","Approfondisci posizione →":"Explore location →","Dove parcheggiare →":"Where to park →","Mare e spiagge →":"Sea and beaches →","Stazione Centrale":"Central Station","Corso Garibaldi":"Corso Garibaldi","1 min a piedi":"1 min walk","5 min a piedi":"5 min walk","7 min a piedi":"7 min walk","10 min a piedi":"10 min walk","Parcheggio":"Parking","Soluzioni gratuite nelle vicinanze":"Free options nearby",
"Informazioni pratiche":"Practical information","Guida ospiti":"Guest guide","Le istruzioni pratiche non occupano più tutta la home: sono raccolte in una guida dedicata, comoda anche quando sei già in appartamento.":"Practical instructions are collected in a dedicated guide that is easy to use during your stay.","Tutte le informazioni pratiche da avere a portata di mano prima e durante il soggiorno a Civico 26.":"All the practical information to keep at hand before and during your stay at Civico 26.","Check-in, Wi‑Fi, acqua, climatizzazione, regole e contatti":"Check-in, Wi-Fi, water, air conditioning, rules and contacts","Tutto ciò che serve prima e durante il soggiorno, compresi parcheggio, raccolta differenziata, autoclave e numeri utili.":"Everything you need before and during your stay, including parking, recycling, the water pump and useful contacts.","Apri Il tuo soggiorno →":"Open your stay guide →","Apri Guida ospiti →":"Open guest guide →",
"Esplora":"Explore","Scopri Reggio e dintorni":"Explore Reggio and surroundings","Scegli la guida che ti interessa: i contenuti completi restano nel sito, ma non sono più tutti ammassati nella home.":"Choose the guide you need: full content remains on the website without cluttering the homepage.","Da vedere":"Sightseeing","Reggio Calabria":"Reggio Calabria","Museo, Lungomare, centro storico e monumenti.":"Museum, seafront, historic centre and monuments.","Apri la guida →":"Open guide →","Costa Viola":"Costa Viola","Mare e spiagge":"Sea and beaches","Scilla, Bagnara e Palmi.":"Scilla, Bagnara and Palmi.","Sapori locali":"Local flavours","Dove mangiare":"Where to eat","Bar, gelaterie, pizzerie, trattorie e ristoranti.":"Cafés, gelato shops, pizzerias, trattorias and restaurants.","Natura":"Nature","Aspromonte":"Aspromonte","Gambarie, boschi e montagna reggina.":"Gambarie, forests and the mountains above Reggio.","Organizza le giornate":"Plan your days","Itinerari":"Itineraries","Reggio, Scilla, weekend senza auto e Aspromonte.":"Reggio, Scilla, a car-free weekend and Aspromonte.","Scegli itinerario →":"Choose itinerary →","Informazioni utili":"Useful information","Mappa e indicazioni per la sosta vicino a Civico 26.":"Map and parking information near Civico 26.","Guarda la mappa →":"View map →","Prima di prenotare":"Before booking","Domande frequenti":"Frequently asked questions","Capienza, servizi, posizione, animali e prenotazione.":"Capacity, amenities, location, pets and booking.","Leggi le FAQ →":"Read FAQs →","Scelti da noi":"Our picks","I nostri preferiti":"Our favourites","I posti e le esperienze che consiglieremmo a un amico.":"The places and experiences we would recommend to a friend.","Cultura & creatività":"Culture & creativity","Arte al Civico 26":"Art at Civico 26","Scopri l'opera esposta nell'appartamento e l'artista.":"Discover the artwork displayed in the apartment and the artist.","Tutto in un punto":"Everything in one place","Guida di Reggio Calabria":"Reggio Calabria guide","La pagina-hub con tutti i collegamenti per organizzare il soggiorno.":"The hub page with all the links you need to plan your stay.","Apri la guida completa →":"Open the complete guide →",
"Posizione":"Location","FAQ":"FAQ","Contatti":"Contacts"
};
const originals=new Map();
function translateNode(node,lang){
 if(!originals.has(node)) originals.set(node,node.nodeValue);
 const original=originals.get(node);
 if(lang==='it'){node.nodeValue=original;return}
 const leading=(original.match(/^\s*/)||[''])[0], trailing=(original.match(/\s*$/)||[''])[0], core=original.trim();
 if(!core)return;
 if(translations[core]){node.nodeValue=leading+translations[core]+trailing;return}
 let out=core; for(const [it,en] of Object.entries(translations)){if(out.includes(it)) out=out.split(it).join(en)}
 node.nodeValue=leading+out+trailing;
}
function setLanguage(lang){
 document.documentElement.lang=lang;
 const walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT),nodes=[];
 while(walker.nextNode()){const n=walker.currentNode;if(n.parentElement&&!['SCRIPT','STYLE'].includes(n.parentElement.tagName))nodes.push(n)}
 nodes.forEach(n=>translateNode(n,lang));
 document.title=lang==='en'?'Civico 26 | Holiday apartment in central Reggio Calabria':'Casa vacanze Reggio Calabria centro | Civico 26';
 localStorage.setItem('civico26-lang',lang);
}
document.addEventListener('DOMContentLoaded',()=>{const select=document.getElementById('languageSelect');const saved=localStorage.getItem('civico26-lang')||'it';select.value=saved;setLanguage(saved);select.addEventListener('change',e=>setLanguage(e.target.value))});
