import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";
import {
  bookingFields,
  clean,
  dedupeEntities,
  financeFields,
  materiallyEqual,
  mergeExisting,
  parseCSV,
  parseEntities,
  type Entity,
} from "./parser.ts";

const ADMIN_EMAILS = new Set(["stefanoalfonso@hotmail.it","andrealfonso@live.it"]);
const enc = new TextEncoder();
const CORS={"content-type":"application/json","access-control-allow-origin":"*","access-control-allow-headers":"authorization, x-client-info, apikey, content-type"};
function json(data: unknown,status=200){return new Response(JSON.stringify(data),{status,headers:CORS})}
async function sha(s:string){const b=await crypto.subtle.digest("SHA-256",enc.encode(s));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,"0")).join("")}

Deno.serve(async(req)=>{if(req.method==="OPTIONS")return new Response("ok",{headers:CORS});try{const auth=req.headers.get("authorization")||"",url=Deno.env.get("SUPABASE_URL")!,anon=Deno.env.get("SUPABASE_ANON_KEY")!,service=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;const userClient=createClient(url,anon,{global:{headers:{Authorization:auth}}});const {data:{user},error:ue}=await userClient.auth.getUser();if(ue||!user||!ADMIN_EMAILS.has(String(user.email||"").toLowerCase()))return json({error:"Non autorizzato"},403);const db=createClient(url,service),body=await req.json(),action=String(body.action||"preview");
 if(action==="history"){const {data,error}=await db.from("import_batches").select("id,source,channel,file_name,status,period_start,period_end,rows_total,rows_new,rows_unchanged,rows_updated,rows_conflict,rows_error,created_at,applied_at,rolled_back_at,metadata").order("created_at",{ascending:false}).limit(50);if(error)throw error;return json({batches:data||[]})}
 if(action==="batch"){const id=String(body.batch_id||"");const [{data:b,error:be},{data:r,error:re}]=await Promise.all([db.from("import_batches").select("*").eq("id",id).single(),db.from("import_rows").select("id,row_number,entity_type,source,external_key,classification,target_table,target_id,normalized_data,error_text,applied_action").eq("batch_id",id).order("row_number").limit(500)]);if(be)throw be;if(re)throw re;return json({batch:b,rows:r||[]})}
 if(action==="apply"){const id=String(body.batch_id||"");const {data,error}=await db.rpc("apply_import_batch",{p_batch:id});if(error)throw error;return json({result:data})}
 if(action==="rollback"){const id=String(body.batch_id||"");const {data,error}=await db.rpc("rollback_import_batch",{p_batch:id});if(error)throw error;return json({result:data})}
 if(action==="discard"){const id=String(body.batch_id||"");const {data:b}=await db.from("import_batches").select("status").eq("id",id).single();if(!b||b.status!=="preview")return json({error:"Si possono eliminare solo anteprime non applicate"},409);await db.from("import_rows").delete().eq("batch_id",id);const {error}=await db.from("import_batches").delete().eq("id",id);if(error)throw error;return json({ok:true})}
 if(action!=="preview")return json({error:"Azione non valida"},400);
 const source=String(body.source||"").toLowerCase();if(!["booking","airbnb"].includes(source))return json({error:"Seleziona Booking o Airbnb"},400);const content=String(body.content||"");if(!content.trim())return json({error:"File vuoto"},400);if(content.length>6_000_000)return json({error:"File troppo grande (max 6 MB)"},413);const fileName=String(body.file_name||"report.csv"),channel=["manual","email","api"].includes(body.channel)?body.channel:"manual",fileHash=await sha(content),origin=`${channel}:${fileName}`;
 const {data:prev}=await db.from("import_batches").select("id,status,created_at,rows_total,rows_new,rows_unchanged,rows_updated,rows_conflict,rows_error").eq("source",source).eq("file_hash",fileHash).in("status",["preview","applied"]).order("created_at",{ascending:false}).limit(1).maybeSingle();if(prev)return json({duplicate_file:true,batch:prev,message:prev.status==="applied"?"Questo identico file è già stato applicato.":"Questo identico file ha già un'anteprima aperta."});
 const parsed=parseCSV(content);let entities:Entity[]=[];for(const x of parsed.rows)entities.push(...parseEntities(source,x.row,x.data,origin,parsed.format));entities=dedupeEntities(entities);if(!entities.length)return json({error:"Non ho riconosciuto prenotazioni o movimenti economici. Controlla piattaforma e formato CSV."},422);
 const [{data:hist,error:he},{data:fin,error:fe}]=await Promise.all([db.from("booking_history").select("*").eq("source",source),db.from("platform_finance_ledger").select("*").eq("source",source)]);if(he)throw he;if(fe)throw fe;const histRows=(hist||[]) as Record<string,unknown>[],finRows=(fin||[]) as Record<string,unknown>[],staged:any[]=[];let minD:string|null=null,maxD:string|null=null;
 for(const ent of entities){const fp=await sha(ent.identity);let existing:Record<string,unknown>|undefined,multiple=false,target="",fields:string[]=[];if(ent.entity_type==="reservation"){target="booking_history";fields=bookingFields;const matches=histRows.filter(x=>(ent.external_key&&String(x.external_id||"")===ent.external_key)||String(x.import_fingerprint||"")===fp);existing=matches[0];multiple=matches.length>1}else{target="platform_finance_ledger";fields=financeFields;const n=ent.normalized;const matches=finRows.filter(x=>(n.external_ref&&String(x.external_ref||"")===String(n.external_ref)&&String(x.line_type||"")===String(n.line_type))||String(x.import_fingerprint||"")===fp);existing=matches[0];multiple=matches.length>1}
  let classification="new",before_data=null,after_data=null,error_text=ent.preconflict||null;if(ent.preconflict)classification="conflict";else if(multiple){classification="conflict";error_text="Più righe esistenti corrispondono alla stessa identità"}else if(existing){before_data=existing;const merged=mergeExisting(existing,ent.normalized,fields);after_data=merged;classification=materiallyEqual(existing,merged,ent.normalized,fields)?"unchanged":"update"}
  const d=String((ent.normalized.start_date||ent.normalized.stay_start||ent.normalized.transaction_date||"") as string),de=String((ent.normalized.end_date||ent.normalized.stay_end||ent.normalized.transaction_date||"") as string);if(d){minD=!minD||d<minD?d:minD;maxD=!maxD||d>maxD?d:maxD}if(de)maxD=!maxD||de>maxD?de:maxD;staged.push({row_number:ent.row_number,entity_type:ent.entity_type,source,external_key:ent.external_key,fingerprint:fp,classification,target_table:target,target_id:existing?Number(existing.id):null,raw_data:ent.raw,normalized_data:ent.normalized,before_data,after_data,error_text})}
 const counts={new:0,unchanged:0,update:0,conflict:0,error:0} as Record<string,number>;for(const s of staged)counts[s.classification]=(counts[s.classification]||0)+1;const {data:batch,error:be}=await db.from("import_batches").insert({source,channel,file_name:fileName,file_hash:fileHash,source_message_id:clean(body.source_message_id),original_subject:clean(body.subject),raw_text:content,parser_version:"4",status:"preview",period_start:minD,period_end:maxD,rows_total:staged.length,rows_new:counts.new,rows_unchanged:counts.unchanged,rows_updated:counts.update,rows_conflict:counts.conflict,rows_error:counts.error,metadata:{csv_rows:parsed.rows.length,entity_rows:staged.length,deduplicated_entities:entities.length,delimiter:parsed.delimiter,csv_format:parsed.format,repaired_rows:parsed.repaired_rows},created_by:user.id}).select("*").single();if(be)throw be;for(let i=0;i<staged.length;i+=250){const {error}=await db.from("import_rows").insert(staged.slice(i,i+250).map(x=>({...x,batch_id:batch.id})));if(error){await db.from("import_batches").update({status:"failed",metadata:{error:error.message}}).eq("id",batch.id);throw error}}
 return json({batch,summary:{total:staged.length,new:counts.new,unchanged:counts.unchanged,updated:counts.update,conflict:counts.conflict,error:counts.error},sample:staged.slice(0,12).map(x=>({row_number:x.row_number,entity_type:x.entity_type,external_key:x.external_key,classification:x.classification,normalized_data:x.normalized_data,error_text:x.error_text}))})
 }catch(e){console.error(e);return json({error:e instanceof Error?e.message:String(e)},500)}});
